envName: test

default:
  app:
    destination:
      namespace: test
      server: https://kubernetes.default.svc
    source:
      targetRevision: main


applications:
  guestbook:
    enabled: true
  petclinic:
    enabled: true
  subcharts:
    enabled: true
  apachewebserver:
    enabled: true

