# your override should supply an envName
envName: null

default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    project: default
    source:
      repoURL: https://github.com/rajivml/argodemo
      targetRevision: main
      extraSourceFields: |
        helm:
          valueFiles:
          - values.yaml
      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides


applications:
  pdfservice:
    enabled: false
  mailqueue:
    enabled: false
  apigateway:
    enabled: false
  authservice:
    enabled: false


products:
  pdfservice:
    deploymentOrder: "1"
    enableAutoSync: true
    destination:
      namespace: helm-guestbook
    source:
      path: helm-guestbook
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.pdfservice.deploymentOrder | quote }}
    # ignore diffs in replicas since we're doing HPA
    extraFields: |
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas

  mailqueue:
    deploymentOrder: "2"
    enableAutoSync: true
    destination:
      namespace: spring-petclinic
    source:
      path: spring-petclinic
      # apps can override the default extraSourceFields
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.mailqueue.deploymentOrder | quote }}

  apigateway:
    deploymentOrder: "3"
    enableAutoSync: true
    destination:
      namespace: sub-charts
    source:
      path: sub-charts
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.apigateway.deploymentOrder | quote }}

  authservice:
    deploymentOrder: "4"
    enableAutoSync: true
    destination:
      namespace: apachewebserver
    source:
      path: apachewebserver
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.authservice.deploymentOrder | quote }}


#EndUser specific
ingress:
  host: IP_ADDRESS_OF_KUBERNETES_INSTANCE
orchestrator:
  endpoint: ORCHESTRATOR_IP:ORCHESTRATOR_PORT
identityserver:
  endpoint: IDENTITY_SERVER_IP:IDENTITY_SERVER_PORT
identity:
  accessToken: abcde
sql:
  host: DATABASE_IP
  username: admin
  password: password
dbname:
  aiHelper: ai_helper
  aiDeployer: ai_deployer
  aiPkgManager: ai_pkgmanager
  aiTrainer: ai_trainer
  aiAppManager: ai_appmanager
registry:
  url: 127.0.0.1

imageTag: "2.0"

isAirgap: "false"