# your override should supply an envName
envName: null

default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    project: default
    source:
      repoURL: https://github.com/rajivml/argodemo
      targetRevision: HEAD
      extraSourceFields: |
        helm:
          valueFiles:
          - {{ $.Values.envName }}-values.yaml
      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides


# hyphen (-) not allowed in these keys
deploymentOrder:
  pdfservice: "1"
  mailqueue: "2"
  apigateway: "3"
  authservice: "4"

products:
  pdf-service:
    enabled: false
    destination:
      namespace: pdfservice
    source:
      path: pdf-service
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.pdfservice }}
    # ignore diffs in replicas since we're doing HPA
    extraFields: |
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas

  mailqueue:
    enabled: false
    destination:
      namespace: mailqueue
    source:
      path: mailqueue
      # apps can override the default extraSourceFields
      extraSourceFields: |
        helm:
          valueFiles:
          - my-app-overrides-{{ $.Values.envName }}-values.yaml
          - {{ $.Values.envName }}-values.yaml
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.mailqueue }}

  api-gateway:
    enabled: false
    destination:
      namespace: apigateway
    source:
      path: api-gateway
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.apigateway }}

  auth-service:
    enabled: false
    destination:
      namespace: authservice
    source:
      path: auth-service
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.authservice }}
