# your override should supply an envName
envName: null

# if set, override all Applications to use this project
projectOverride: null


spec:
  retry:
    limit: 2 # number of failed sync attempt retries; unlimited number of attempts if less than 0
    backoff:
      duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
      factor: 2 # a factor to multiply the base duration after each failed retry
      maxDuration: 3m # the maximum amount of time allowed for the backoff strategy


default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    enableAutoSync: null
    autoSyncPrune: true
    destination:
      namespace: null
      server: null
    project: null
    source:
      path: null
      repoURL: https://github.com/rajivml/argodemo
      targetRevision: HEAD

      extraSourceFields: |
        helm:
          valueFiles:
          - {{ $.Values.envName }}-values.yaml
      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides

projects:
  auth:
    description: 'auth services -- api gateway, auth'
    sourceRepos:
    - https://MY_APPS_REPOSITORY/auth/*

  onboarding:
    description: 'onboarding services -- user PII, etc'
    sourceRepos:
    - https://MY_APPS_REPOSITORY/onboarding/*


# hyphen (-) not allowed in these keys
deploymentOrder:
  pdfservice: "1"
  mailqueue: "2"
  apigateway: "3"
  authservice: "4"

applications:

  pdf-service:
    enabled: false
    syncWave: "3"
    destination:
      namespace: pdfservice
      server: null
    project: onboarding
    source:
      path: pdf-service
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.pdfservice }}
    # ignore diffs in replicas since we're doing HPA
    extraFields: |
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas

  mailqueue:
    enabled: false
    destination:
      namespace: mailqueue
      server: null
    project: onboarding
    source:
      path: mailqueue
      # apps can override the default extraSourceFields
      extraSourceFields: |
        helm:
          valueFiles:
          - my-app-overrides-{{ $.Values.envName }}-values.yaml
          - {{ $.Values.envName }}-values.yaml
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.mailqueue }}

  api-gateway:
    enabled: false
    sync-wave: "3"
    destination:
      namespace: apigateway
      server: null
    project: auth
    source:
      path: api-gateway
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.apigateway }}

  auth-service:
    enabled: false
    sync-wave: "4"
    destination:
      namespace: authservice
      server: null
    project: auth
    source:
      path: auth-service
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.deploymentOrder.authservice }}
