# your override should supply an envName
envName: null


applications:
  apps:
    guestbook:
      enabled: false
    petclinic:
      enabled: false
    subcharts:
      enabled: false
    apachewebserver:
      enabled: false
  userInputs:
    ingress:
      host: IP_ADDRESS_OF_KUBERNETES_INSTANCE
    orchestrator:
      endpoint: ORCHESTRATOR_IP:ORCHESTRATOR_PORT
    identityserver:
      endpoint: IDENTITY_SERVER_IP:IDENTITY_SERVER_PORT
    identity:
      accessToken: abcde
    sql:
      host: DATABASE_IP
      username: admin
      password: password
    dbname:
      aiHelper: ai_helper
      aiDeployer: ai_deployer
      aiPkgManager: ai_pkgmanager
      aiTrainer: ai_trainer
      aiAppManager: ai_appmanager
    registry:
      url: 127.0.0.1
    imageTag: "2.0"
    isAirgap: "false"

doNotTouch:

  default:
    project:
      roles: |
        - name: read-only
          description: Read-only privileges within project
          policies:
          - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
        - name: ci-role
          description: Role to allow CICD pipeline to sync apps within project
          policies:
          - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
      destinations: |
        - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
          server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
    app:
      project: default
      enableAutoSync: true
      source:
        repoURL: https://github.com/rajivml/argodemo
        targetRevision: main
        extraSourceFields: |
          helm:
            valueFiles:
            - values.yaml
        #  kustomize:
        #    namePrefix: prod-
      #extraFields: |
      #  Default fields you want on all applications, unless the app individually overrides

  products:
    guestbook:
      deploymentOrder: "1"
      destination:
        namespace: helm-guestbook
      source:
        path: helm-guestbook
      extraAnnotations: |
        annotations:
          argocd.argoproj.io/sync-wave: {{ $.Values.products.guestbook.deploymentOrder | quote }}
      # ignore diffs in replicas since we're doing HPA
      extraFields: |
        ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
          - /spec/replicas

    petclinic:
      deploymentOrder: "2"
      destination:
        namespace: spring-petclinic
      source:
        path: spring-petclinic
        # apps can override the default extraSourceFields
      extraAnnotations: |
        annotations:
          argocd.argoproj.io/sync-wave: {{ $.Values.products.petclinic.deploymentOrder | quote }}

    subcharts:
      deploymentOrder: "3"
      destination:
        namespace: sub-charts
      source:
        path: sub-charts
      extraAnnotations: |
        annotations:
          argocd.argoproj.io/sync-wave: {{ $.Values.products.subcharts.deploymentOrder | quote }}

    apachewebserver:
      deploymentOrder: "4"
      destination:
        namespace: apachewebserver
      source:
        path: apachewebserver
      extraAnnotations: |
        annotations:
          argocd.argoproj.io/sync-wave: {{ $.Values.products.apachewebserver.deploymentOrder | quote }}


