# your override should supply an envName
envName: null

default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    project: default
    source:
      repoURL: https://github.com/rajivml/argodemo
      targetRevision: HEAD
      extraSourceFields: |
        helm:
          valueFiles:
          - {{ $.Values.envName }}-values.yaml
      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides


applications:
  pdfservice:
    enabled: false
  mailqueue:
    enabled: false
  apigateway:
    enabled: false
  authservice:
    enabled: false


products:
  pdfservice:
    deploymentOrder: "1"
    enableAutoSync: true
    destination:
      namespace: pdfservice
    source:
      path: pdf-service
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.pdfservice.deploymentOrder }}
    # ignore diffs in replicas since we're doing HPA
    extraFields: |
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas

  mailqueue:
    deploymentOrder: "2"
    enableAutoSync: true
    destination:
      namespace: mailqueue
    source:
      path: mailqueue
      # apps can override the default extraSourceFields
      extraSourceFields: |
        helm:
          valueFiles:
          - my-app-overrides-{{ $.Values.envName }}-values.yaml
          - {{ $.Values.envName }}-values.yaml
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.mailqueue.deploymentOrder }}

  apigateway:
    deploymentOrder: "3"
    enableAutoSync: true
    destination:
      namespace: apigateway
    source:
      path: api-gateway
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.apigateway.deploymentOrder }}

  authservice:
    deploymentOrder: "4"
    enableAutoSync: true
    destination:
      namespace: authservice
    source:
      path: auth-service
    extraAnnotations: |
      annotations:
        argocd.argoproj.io/sync-wave: {{ $.Values.products.authservice.deploymentOrder }}
