resources:
- ./all.yaml
images:
- name: uipath/spring-petclinic
  newName: DOCKER_REGISTRY_IP/uipath/spring-petclinic
  newTag: "latest"
patches:
- path: overlays/patch_image_pull_secret_daemonset.yaml
  target:
    kind: DaemonSet
- path: overlays/patch_image_pull_secret_deployment.yaml
  target:
    kind: Deployment
- path: overlays/patch_image_pull_secret_job.yaml
  target:
    kind: Job
- path: overlays/patch_image_pull_secret_pod.yaml
  target:
    kind: Pod
- path: overlays/patch_image_pull_secret_statefulset.yaml
  target:
    kind: SatefulSet