---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-helm-hooks
data:
  hook.sh: |+
{{ .Files.Get "hooks/namespace-hook.sh" | indent 4 }}

{{/*
You can use ConfigMap helper:
{{- (.Files.Glob "hooks/*").AsConfig | nindent 2 }}

Don't forget to update annotation in Deployment.
*/}}
