---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-helm-acc

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: example-helm
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: example-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-helm
subjects:
  - kind: ServiceAccount
    name: example-helm-acc
    namespace: {{ .Release.Namespace }}
