imageCredentials:
  name: chart1-registry-cred
  registry: "chart1-registry"
  username: "chart1-user"
  password: "chart1-password"
namespace: subcharts

favorite:
  drink: coffee
  food: pizza
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions

dessert: frooti
imageTag: "1.0"