resources:
- backend.yaml
- frontend.yaml
- maintenance-page-up.yaml
- maintenance-page-down.yaml
- upgrade-sql-schema.yaml
images:
- name: nginx:latest
  newName: DOCKER_REGISTRY_IP/nginx
  newTag: "latest"
- name: alpine:latest
  newName: DOCKER_REGISTRY_IP/alpine
  newTag: "latest"
patches:
- path: overlays/patch_image_pull_secret_daemonset.yaml
  target:
    kind: DaemonSet
- path: overlays/patch_image_pull_secret_deployment.yaml
  target:
    kind: Deployment
- path: overlays/patch_image_pull_secret_job.yaml
  target:
    kind: Job
- path: overlays/patch_image_pull_secret_pod.yaml
  target:
    kind: Pod
- path: overlays/patch_image_pull_secret_statefulset.yaml
  target:
    kind: SatefulSet