apiVersion: batch/v1
kind: Job
metadata:
  generateName: upgrade-sql
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
  backoffLimit: 0