---
apiVersion: v1
kind: Namespace
metadata:
  name: secret-copier
  annotations:
    argocd.argoproj.io/sync-wave: "-101"


---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: secret-copier
  name: post-provision
  annotations:
    argocd.argoproj.io/sync-wave: "-101"

---
# spinnaker-clusterrolebinding.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: post-provision-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-101"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: post-provision
  namespace: secret-copier

---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: secret-copier
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  containers:
  - name: shell-operator
    image: uipath/secret-copier:0.1
    imagePullPolicy: Always
  serviceAccountName: post-provision

