---
apiVersion: v1
kind: Namespace
metadata:
  name: secret-copier
  annotations:
    argocd.argoproj.io/sync-wave: "-101"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: secret-copier
  name: secret-copier-acc
  annotations:
    argocd.argoproj.io/sync-wave: "-100"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: secret-copier
  name: secret-copier
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: secret-copier
  name: secret-copier
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-copier
subjects:
  - kind: ServiceAccount
    name: secret-copier-acc
    namespace: secret-copier

---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: secret-copier
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  containers:
  - name: shell-operator
    image: uipath/secret-copier:0.1
    imagePullPolicy: Always
  serviceAccountName: secret-copier-acc

