resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newName: DOCKER_REGISTRY_IP/gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.2"
patches:
- path: overlays/patch_image_pull_secret_daemonset.yaml
  target:
    kind: DaemonSet
- path: overlays/patch_image_pull_secret_deployment.yaml
  target:
    kind: Deployment
- path: overlays/patch_image_pull_secret_job.yaml
  target:
    kind: Job
- path: overlays/patch_image_pull_secret_pod.yaml
  target:
    kind: Pod
- path: overlays/patch_image_pull_secret_statefulset.yaml
  target:
    kind: SatefulSet

namePrefix: kustomize-
