apiVersion: batch/v1
kind: Job
metadata:
  name: "preflight-checks"
  namespace: default
  generateName: preflight-checks
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: provision
      imagePullSecrets:
      - name: kotsadm-replicated-registry
      containers:
      - name: preflights-aif
        image: aifabriconprem.azurecr.io/on-prem/preflight-checks:argocd
        imagePullPolicy: Always
        command: ["echo 'hello world'; exit 0"]
      restartPolicy: Never