resources:
- ./manifests.yaml
images:
- name: alpine
  newName: DOCKER_REGISTRY_IP/alpine
  newTag: "latest"
- name: ngnix
  newName: DOCKER_REGISTRY_IP/ngnix
  newTag: "latest"
patches:
- path: overlays/patch_image_pull_secret_daemonset.yaml
  target:
    kind: DaemonSet
- path: overlays/patch_image_pull_secret_deployment.yaml
  target:
    kind: Deployment
- path: overlays/patch_image_pull_secret_job.yaml
  target:
    kind: Job
- path: overlays/patch_image_pull_secret_pod.yaml
  target:
    kind: Pod
- path: overlays/patch_image_pull_secret_statefulset.yaml
  target:
    kind: SatefulSet

namePrefix: kustomize-
