apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui-2
  template:
    metadata:
      labels:
        app: guestbook-ui-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui-2
        ports:
        - containerPort: 80
        env:
          - name: DESSERT
            valueFrom:
              configMapKeyRef:
                name: chart2
                key: dessert
          - name: EXTRAS
            value: "{{ .Values.dessert }}"
          - name: IMAGE_CREDENTIALS_NAME
            value: {{ $imageCredentials.name }}
          - name: IMAGE_CREDENTIALS_REGISTRY
            value: {{ $imageCredentials.registry }}
          - name: REGISTRY_USERNAME
            value: {{ $imageCredentials.username }}
          - name: REGISTRY_PASSWORD
            value: {{ $imageCredentials.password }}
          - name: IMAGE_TAG
            valueFrom:
              configMapKeyRef:
                name: service-fabric-config
                key: IMAGE_TAG
          - name: IMAGE_TAG_VALUES
            value: "{{ {{ $imageTag }}"

