apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui-2
  template:
    metadata:
      labels:
        app: guestbook-ui-2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui-2
        ports:
        - containerPort: 80
        env:
          - name: DESSERT
            valueFrom:
              configMapKeyRef:
                name: chart2
                key: dessert
          - name: EXTRAS
            value: "{{ .Values.dessert }}"

