apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: provision
  name: aifabricdeployment
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: provision
      imagePullSecrets:
      - name: kotsadm-replicated-registry
      containers:
      - image: aifabriconprem.azurecr.io/on-prem/daemon-script:v20.10.1
        name: daemon-script
        imagePullPolicy: Always
        env:
        - name: INGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: ingressHost
        - name: ORCHESTRATOR_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: orchestratorEndpoint
        - name: IDENTITY_SERVER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: identityserverEndpoint
        - name: IS_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: accessToken
        - name: PLATFORM
          value: 'onebox'
        - name: SQL_HOST
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: sqlHost
        - name: SQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: sqlUsername
        - name: SQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: sqlPassword
        - name: SERVICES_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: registryURL
        - name: SERVICES_PROJECT
          value: on-prem
        - name: REPLICATED_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: registryURL
        - name: REPLICATED_PROJECT
          value: on-prem
        - name: REPLICATED_NAMESPACE
          value: default
        - name: HELPER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: helperDBName
        - name: PKGMANAGER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: pkgDBName
        - name: DEPLOYER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: deployerDBName
        - name: TRAINER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: trainerDBName
        - name: APPMANAGER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: service-fabric-config
              key: appDBName
        - name: TEST_PATH_STATUS
          value: 'disable'
        - name: APP_RELEASE
          value: 'v20.10.1.1'
        - name: HELPER_RELEASE
          value: 'v20.10.1'
        - name: PKGMANAGER_RELEASE
          value: 'v20.10.1'
        - name: DEPLOYER_RELEASE
          value: 'v20.10.1.1'
        - name: TRAINER_RELEASE
          value: 'v20.10.1'
        - name: APPMANAGER_RELEASE
          value: 'v20.9.2'
        - name: APPMANAGER_HELPER_RELEASE
          value: 'v20.9.2'
        - name: DATAMANAGER_RELEASE
          value: '20.9.1-prod'
        - name: IS_AIRGAP
          value: "false"
        - name: METADATA_BRANCH
          value: master
      restartPolicy: Never
