---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: uipath/secret-copier:0.1
    imagePullPolicy: Always
  serviceAccountName: secret-copier-acc
