ingress:
  host: localhost
orchestrator:
  endpoint: localhost
identityserver:
  endpoint: localhost
identity:
  accessToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjUzRjE2Q0UyQjg3RTQ1RUU1RDgwOTRERjc5NjJEN0MzOTYxNjcyN0UiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJVX0ZzNHJoLVJlNWRnSlRmZVdMWHc1WVdjbjQifQ
sql:
  host: localhost
  username: admin
  password: password
dbname:
  aiHelper: ai_helper
  aiDeployer: ai_deployer
  aiPkgManager: ai_pkgmanager
  aiTrainer: ai_trainer
  aiAppManager: ai_appmanager
registry:
  servicesRegistry: aifabriconprem.azurecr.io/on-prem
  servicesProject: on-prem
  replicatedRegistry: aifabriconprem.azurecr.io
  replicatedProject: on-prem
  Namespace: default
  isAirgap: false
  metadataBranch: master